"""
Generates a digital compliance report (PDF) for a single Scan record.
Uses reportlab so the app has zero external binary dependency (e.g. no
wkhtmltopdf) beyond the pure-Python/C-extension packages in requirements.txt.
"""
import os
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image as RLImage
)


def build_report(scan, product, violations, output_path: str):
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "TitleX", parent=styles["Title"], fontSize=16, spaceAfter=4
    )
    subtitle_style = ParagraphStyle(
        "Subtitle", parent=styles["Normal"], fontSize=10, textColor=colors.grey
    )
    heading_style = ParagraphStyle(
        "HeadingX", parent=styles["Heading2"], fontSize=12, spaceBefore=14
    )

    doc = SimpleDocTemplate(output_path, pagesize=A4,
                             topMargin=20 * mm, bottomMargin=18 * mm)
    story = []

    story.append(Paragraph("Legal Metrology Compliance Report", title_style))
    story.append(Paragraph(
        "Legal Metrology (Packaged Commodities) Rules, 2011 &ndash; automated "
        "label compliance assessment", subtitle_style))
    story.append(Spacer(1, 10 * mm))

    meta_data = [
        ["Report generated", datetime.utcnow().strftime("%d-%b-%Y %H:%M UTC")],
        ["Scan ID", str(scan.id)],
        ["Product", product.name],
        ["Brand", product.brand or "-"],
        ["Category", product.category or "-"],
        ["Inspecting officer", scan.inspector.username],
        ["Overall status", scan.status.upper().replace("_", " ")],
        ["Compliance score", f"{scan.compliance_score} / 100"],
    ]
    meta_table = Table(meta_data, colWidths=[55 * mm, 110 * mm])
    meta_table.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#555555")),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("LINEBELOW", (0, 0), (-1, -1), 0.4, colors.HexColor("#dddddd")),
    ]))
    story.append(meta_table)

    if scan.image_path and os.path.exists(scan.image_path):
        story.append(Spacer(1, 6 * mm))
        try:
            story.append(RLImage(scan.image_path, width=90 * mm, height=90 * mm,
                                  kind="proportional"))
        except Exception:
            pass

    story.append(Paragraph("Violations Identified", heading_style))
    if violations:
        rows = [["Rule", "Field", "Severity", "Description"]]
        for v in violations:
            rows.append([v.rule_code, v.field, v.severity.upper(), v.description])
        vt = Table(rows, colWidths=[28 * mm, 28 * mm, 20 * mm, 89 * mm])
        vt.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1f2937")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("GRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#dddddd")),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1),
             [colors.white, colors.HexColor("#f7f7f7")]),
        ]))
        story.append(vt)
    else:
        story.append(Paragraph("No violations detected.", styles["Normal"]))

    story.append(Paragraph("Raw OCR Extract (for manual verification)", heading_style))
    ocr_preview = (scan.raw_ocr_text or "").strip()[:1500]
    story.append(Paragraph(ocr_preview.replace("\n", "<br/>") or "-", styles["Code"]))

    story.append(Spacer(1, 10 * mm))
    story.append(Paragraph(
        "This report was generated by an automated system and is intended to "
        "assist, not replace, human inspection under the Legal Metrology "
        "Act, 2009. Fields marked as violations should be manually verified "
        "before formal enforcement action.",
        ParagraphStyle("Disclaimer", parent=styles["Normal"], fontSize=8,
                        textColor=colors.grey)))

    doc.build(story)
    return output_path
