"""
Report Generator Service for Legal Metrology Compliance System.

Generates structured audit reports, printable HTML, and PDF export with
SHA-256 tamper-evident digital signatures and statutory disclaimers.
"""

import hashlib
import json
import logging
import os
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)

STATUTORY_DISCLAIMER = (
    "DISCLAIMER: This report is generated by an AI-assisted Legal Metrology compliance "
    "inspection assistance system. It is designed to assist enforcement authorities, legal metrology "
    "officers, and packaging inspectors. It does not replace the official statutory inspection process, "
    "and final legal determinations rest exclusively with the competent statutory authorities "
    "under the Legal Metrology Act, 2009 and Legal Metrology (Packaged Commodities) Rules, 2011."
)


def compute_sha256_signature(payload: Dict[str, Any]) -> str:
    """Compute a deterministic SHA-256 hash of the report data for audit and tamper-evidence."""
    clean_copy = {k: v for k, v in payload.items() if k not in ("report_hash", "tamper_evidence_hash")}
    clean_json = json.dumps(clean_copy, sort_keys=True, default=str)
    return hashlib.sha256(clean_json.encode("utf-8")).hexdigest()


def generate_report_data(
    inspection: Dict[str, Any],
    product: Optional[Dict[str, Any]],
    fields: List[Dict[str, Any]],
    compliance_results: List[Dict[str, Any]],
    summary_stats: Optional[Dict[str, Any]] = None,
    inspector_name: str = "Authorized Inspector",
    images: Optional[List[Dict[str, Any]]] = None,
    ocr_summary: Optional[Dict[str, Any]] = None
) -> Dict[str, Any]:
    """
    Build the complete audit report dictionary ready for persistence and rendering.
    """
    now_utc = datetime.now(timezone.utc)
    inspection_id = str(inspection.get("id", "N/A"))

    violations = [r for r in compliance_results if r.get("status") == "VIOLATION"]
    reviews = [r for r in compliance_results if r.get("status") == "REVIEW"]
    passes = [r for r in compliance_results if r.get("status") == "PASS"]

    if summary_stats is None:
        overall_res = "VIOLATION" if violations else ("REVIEW" if reviews else "PASS")
        summary_stats = {
            "total_rules_checked": len(compliance_results),
            "pass_count": len(passes),
            "review_count": len(reviews),
            "violation_count": len(violations),
            "overall_result": overall_res
        }

    base_payload = {
        "report_id": f"REP-{inspection_id[:8].upper()}-{int(now_utc.timestamp())}",
        "inspection_id": inspection_id,
        "generated_at": now_utc.isoformat(),
        "inspector": inspector_name,
        "product_metadata": {
            "title": inspection.get("title", "Packaged Commodity"),
            "category": inspection.get("product_category", "Packaged Commodity"),
            "brand": product.get("brand") if product else None,
            "product_name": product.get("product_name") if product else None,
            "images_count": len(images or [])
        },
        "overall_result": summary_stats.get("overall_result", "REVIEW"),
        "summary": summary_stats,
        "counts": {
            "total_rules": len(compliance_results),
            "pass_count": len(passes),
            "review_count": len(reviews),
            "violation_count": len(violations)
        },
        "extracted_declarations": fields,
        "compliance_findings": compliance_results,
        "violations": violations,
        "review_required": reviews,
        "statutory_disclaimer": STATUTORY_DISCLAIMER
    }

    # Generate cryptographic audit hash
    audit_hash = compute_sha256_signature(base_payload)
    base_payload["report_hash"] = audit_hash
    base_payload["tamper_evidence_hash"] = audit_hash

    return base_payload


def render_html_report(report_data: Dict[str, Any]) -> str:
    """
    Render a clean, professional government/enterprise inspection report in HTML.
    Designed for printability and PDF conversion.
    """
    overall = report_data.get("overall_result", "REVIEW")
    badge_color = {
        "PASS": "#166534",
        "REVIEW": "#854d0e",
        "VIOLATION": "#991b1b"
    }.get(overall, "#1e3a5f")

    badge_bg = {
        "PASS": "#dcfce7",
        "REVIEW": "#fef9c3",
        "VIOLATION": "#fee2e2"
    }.get(overall, "#e2e8f0")

    findings_rows = ""
    for r in report_data.get("compliance_findings", []):
        st = r.get("status", "REVIEW")
        color = "#166534" if st == "PASS" else ("#991b1b" if st == "VIOLATION" else "#854d0e")
        bg = "#dcfce7" if st == "PASS" else ("#fee2e2" if st == "VIOLATION" else "#fef9c3")
        source = r.get("legal_source", {}) or {}
        rule_cit = f"{source.get('document', '')} - {source.get('rule', '')}"

        findings_rows += f"""
        <tr>
            <td style="padding: 10px; border-bottom: 1px solid #e2e8f0; font-weight: 500;">{r.get('field_name', '')}</td>
            <td style="padding: 10px; border-bottom: 1px solid #e2e8f0;">{r.get('detected_value') or '<span style="color:#94a3b8;">Not Detected</span>'}</td>
            <td style="padding: 10px; border-bottom: 1px solid #e2e8f0;">{r.get('required_value', '')}</td>
            <td style="padding: 10px; border-bottom: 1px solid #e2e8f0;">
                <span style="display:inline-block; padding: 2px 8px; border-radius: 4px; font-weight: bold; font-size: 12px; color: {color}; background-color: {bg};">
                    {st}
                </span>
            </td>
            <td style="padding: 10px; border-bottom: 1px solid #e2e8f0; font-size: 13px;">{r.get('reason', '')}</td>
            <td style="padding: 10px; border-bottom: 1px solid #e2e8f0; font-size: 12px; color: #475569;">{rule_cit}</td>
        </tr>
        """

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Compliance Inspection Report - {report_data.get('inspection_id')}</title>
    <style>
        @page {{
            size: A4;
            margin: 1.5cm;
        }}
        body {{
            font-family: 'Segoe UI', Arial, sans-serif;
            color: #0f172a;
            line-height: 1.5;
            margin: 0;
            padding: 24px;
            background-color: #ffffff;
        }}
        .header {{
            border-bottom: 3px solid #1e3a5f;
            padding-bottom: 16px;
            margin-bottom: 24px;
            display: flex;
            justify-content: space-between;
            align-items: flex-start;
        }}
        .title {{
            font-size: 22px;
            font-weight: 800;
            color: #1e3a5f;
            margin: 0 0 4px 0;
            text-transform: uppercase;
        }}
        .subtitle {{
            font-size: 13px;
            color: #475569;
            margin: 0;
        }}
        .badge-large {{
            font-size: 16px;
            font-weight: bold;
            padding: 8px 18px;
            border-radius: 6px;
            color: {badge_color};
            background-color: {badge_bg};
            display: inline-block;
            text-align: center;
        }}
        .meta-grid {{
            display: grid;
            grid-template-columns: repeat(3, 1fr);
            gap: 16px;
            background-color: #f8fafc;
            padding: 16px;
            border-radius: 8px;
            margin-bottom: 24px;
            border: 1px solid #e2e8f0;
        }}
        .meta-item label {{
            font-size: 11px;
            text-transform: uppercase;
            color: #64748b;
            font-weight: 600;
            display: block;
        }}
        .meta-item value {{
            font-size: 14px;
            color: #0f172a;
            font-weight: 600;
            display: block;
            margin-top: 2px;
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 24px;
        }}
        th {{
            background-color: #1e3a5f;
            color: #ffffff;
            font-weight: 600;
            font-size: 12px;
            text-transform: uppercase;
            text-align: left;
            padding: 10px;
        }}
        .hash-box {{
            background-color: #f1f5f9;
            border-left: 4px solid #1e3a5f;
            padding: 12px;
            margin-top: 24px;
            font-family: monospace;
            font-size: 11px;
            word-break: break-all;
        }}
        .disclaimer {{
            font-size: 11px;
            color: #64748b;
            margin-top: 16px;
            font-style: italic;
            border-top: 1px solid #e2e8f0;
            padding-top: 12px;
        }}
    </style>
</head>
<body>

    <div class="header">
        <div>
            <h1 class="title">Legal Metrology Compliance Report</h1>
            <p class="subtitle">Packaged Commodities Rules, 2011 Inspection Verification</p>
            <p class="subtitle" style="margin-top: 4px;">Inspection ID: <strong>{report_data.get('inspection_id')}</strong></p>
        </div>
        <div style="text-align: right;">
            <span class="badge-large">{overall}</span>
            <div style="font-size: 11px; color: #64748b; margin-top: 6px;">
                Generated: {report_data.get('generated_at')[:10]}
            </div>
        </div>
    </div>

    <div class="meta-grid">
        <div class="meta-item">
            <label>Commodity / Product</label>
            <value>{report_data.get('product_metadata', {}).get('title', 'Packaged Product')}</value>
        </div>
        <div class="meta-item">
            <label>Category</label>
            <value>{report_data.get('product_metadata', {}).get('category', 'Standard Package')}</value>
        </div>
        <div class="meta-item">
            <label>Inspector</label>
            <value>{report_data.get('inspector', 'Authorized Inspector')}</value>
        </div>
        <div class="meta-item">
            <label>Rules Checked</label>
            <value>{report_data.get('counts', {}).get('total_rules', 0)} Rules</value>
        </div>
        <div class="meta-item">
            <label>Compliant (Pass)</label>
            <value style="color: #166534;">{report_data.get('counts', {}).get('pass_count', 0)} Declarations</value>
        </div>
        <div class="meta-item">
            <label>Review / Violations</label>
            <value style="color: #991b1b;">
                {report_data.get('counts', {}).get('review_count', 0)} Review / {report_data.get('counts', {}).get('violation_count', 0)} Violations
            </value>
        </div>
    </div>

    <h2 style="font-size: 16px; color: #1e3a5f; margin: 0 0 12px 0;">Statutory Compliance Verification Checklist</h2>

    <table>
        <thead>
            <tr>
                <th>Field</th>
                <th>Detected Value</th>
                <th>Statutory Requirement</th>
                <th>Result</th>
                <th>Evaluation Reason</th>
                <th>Legal Provision</th>
            </tr>
        </thead>
        <tbody>
            {findings_rows}
        </tbody>
    </table>

    <div class="hash-box">
        <strong>SHA-256 Cryptographic Audit Signature:</strong><br>
        {report_data.get('report_hash')}
    </div>

    <div class="disclaimer">
        {report_data.get('statutory_disclaimer')}
    </div>

</body>
</html>
"""
    return html


def export_report_pdf(html_content: str, output_path: str) -> Optional[str]:
    """
    Convert HTML report to PDF using WeasyPrint.
    If WeasyPrint is unavailable, saves the HTML report directly as a fallback.
    """
    try:
        from weasyprint import HTML
        HTML(string=html_content).write_pdf(output_path)
        return output_path
    except ImportError:
        logger.warning("WeasyPrint not installed. Saving HTML report directly.")
        html_path = output_path.replace(".pdf", ".html")
        with open(html_path, "w", encoding="utf-8") as f:
            f.write(html_content)
        return html_path
    except Exception as e:
        logger.error(f"PDF generation failed: {e}. Writing HTML fallback.")
        html_path = output_path.replace(".pdf", ".html")
        with open(html_path, "w", encoding="utf-8") as f:
            f.write(html_content)
        return html_path
